baseURL = "https://DasherAmtlich.github.io/"
title = "Dasher"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true

  author = "Dasher Amtlich"

[taxonomies]
  category = "categories"
<<<<<<< HEAD
  tag = "tags"
=======
  tag = "tags"
  
>>>>>>> c08d13ecfc7a489f8d84b0722f593a55b3492ffb
