baseURL = "https://DasherAmtlich.github.io/"
title = "Dasher"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true

  author = "Dasher Amtlich"

[taxonomies]
  category = "categories"
  tag = "tags"

  [markup]
   [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe=true
